server:
  port: 3000
eureka:
  server:
    enable-self-preservation: false  #关闭自我保护机制
    eviction-interval-timer-in-ms: 40000 #设置间隔清理时间（单位毫秒）
  instance:
    hostname: localhost
  client:
    register-with-eureka: false   #不把自己当做客户端注册到eureka上
    fetch-registry: false    #不需要从服务端获取注册信息
    service-url:
      defaultZone: http://localhost:3000/eureka